### PR TITLE
Updates from bedrock

### PR DESCRIPTION
**Pull request by MozmarRobot**
From file changes in https://github.com/mozilla/bedrock/commit/1f1c7fc5c9b6b722ecb6cf70bb61ffb1463cd246

### CODE REVIEW

**Review by flodolo — CHANGES_REQUESTED** [review]
@reemhamz 

Since we're updating these strings, we should get rid of all the Fluent terms that refer to non Mozilla products.

**Comment by reemhamz** [comment]
In this case, since you're referring to the PR removing instances of the IE string, do you mean remove any mention of the IE terms or for all Fluent terms that are not Mozilla products?

**Comment by flodolo** [comment]
All non-Mozilla products (`{ -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera },  { -brand-name-ie }`).

Feel free to tag me in the Bedrock PR for review. Note that you don't need to update the string ID, you can just fix the new strings, since they have not been exposed yet in Pontoon.

**Comment by reemhamz** [comment]
I can make that change in a different PR since this one was mainly tackling the IE stuff. I can definitely tag you in that PR when I work on it 👍🏼 

> Note that you don't need to update the string ID, you can just fix the new strings, since they have not been exposed yet in Pontoon.

Sorry, I think I'm getting a little lost in translation (pun intended) here. Do you mean to just do it the typical way we've been doing it (make the old string obsolete and make a new string ID with `-v(#)` at the end of it without using those string IDs for the non-Mozilla products?

Also, do we want to update _all_ Fluent strings we have if they have non-Mozilla Fluent terms? Or should this just be the case going forward and to leave the old Fluent strings as they are?

**Comment by flodolo** [comment]
> Sorry, I think I'm getting a little lost in translation (pun intended) here. Do you mean to just do it the typical way we've been doing it (make the old string obsolete and make a new string ID with `-v(#)` at the end of it without using those string IDs for the non-Mozilla products?

No, I'm saying NOT to do it the usual way 😉 

If a string is already exposed for localization, we need to have it retranslated. That's done by versioning the existing ID (e.g. add `-v1`), changing the text, and keeping the previous string around as "obsolete" (so we can use that while the new string is being translated).

These strings are stuck in review, so they're not exposed for localization yet. That means that you can update the text directly without versioning the ID.

> Also, do we want to update _all_ Fluent strings we have if they have non-Mozilla Fluent terms? Or should this just be the case going forward and to leave the old Fluent strings as they are?

No. We only update strings when we need to make other changes (like in this case), so we can progressively get rid of these terms without asking localizers to retranslate a ton of strings at once.

**Comment by reemhamz** [comment]
Thanks for explaining! I'm getting this change done right now. I'll tag you in the PR

**Review by peiying2 — APPROVED** [review]
LGTM. @flodolo please take another pass of this.

**Review by flodolo — APPROVED** [review]

**Pull request merged**
