### PR TITLE
Updates from bedrock

### PR DESCRIPTION
**Pull request by MozmarRobot**
From file changes in https://github.com/mozilla/bedrock/commit/2580cba00e8c68a726453fe18426d7306a7675f9

### CODE REVIEW

**Comment by peiying2** [comment]
@alexgibson has the process changed between bedrock and www-l10n when a PR is generated? I saw this PR but was waiting for a review request, which indicates that the PR is ready for review. Then came the second PR: https://github.com/mozilla-l10n/www-l10n/pull/89. The two are for the same file, one is an update from the other. Can we have the changes to the same file shown in the same PR instead of a new one? I've noticed this process change from reviewing the works by other devs a couple of weeks ago.  Let me know so I can be better prepared. Thank you.

**Comment by alexgibson** [comment]
@peiying2 nothing has changed here in terms of process. PRs are automated after each merge to master in bedrock, and the hope is you will see those and review / merge them. I think devs have been requesting review from you in case you didn't notice the PR. I think it's safe to assume every merge to master should result in a PR here that is ready for review as soon as it's opened.

There's a merge conflict here since the other PR merged first, so I'll manually open a new one to replace this.

**Comment by alexgibson** [comment]
Oh wait I see - the second automated PR also included the changes here, since this PR had not been merged yet. With that, there's nothing to do here and this PR can be closed (I'll leave that for you do do here so you have time to read comments and respond if needed). Thanks

**Comment by peiying2** [comment]
> Oh wait I see - the second automated PR also included the changes here, since this PR had not been merged yet. With that, there's nothing to do here and this PR can be closed (I'll leave that for you do do, so you have time to read comments and respond if needed). Thanks

I will follow the new approach and review the PR without getting a ping. Thank you.

**Pull request closed without merging**
