### PR TITLE
Welsh - Remove links using the now-deleted `vr` URL variable on Browser History page

### PR DESCRIPTION
**Pull request by stevejalim**
When the Mixed Reality site was sunsetted, the `vr` URL variable disappeared from the HTML template, breaking the Welsh translation keys `browser-history-in-the-future-the` and `browser-history-in-the-future-the-v2`. This change remedies that by keeping the copy the same and just removing the hyperlink markup

### CODE REVIEW

**Comment by stevejalim** [comment]
@rprys and @craigcook - would you mind sense-checking what I've done here, please? Diolch yn fawr!

**Comment by peiying2** [comment]
> @rprys and @craigcook - would you mind sense-checking what I've done here, please? Because it's a community/Pontoon translation, I don't know whether I need to fix it further upstream or just here. Diolch yn fawr!

Thank you. Let me share this with the contributor and let you know..

**Comment by peiying2** [comment]
Looks like the same issue exists in other languages in the other PR pending review/approval. I don't think there will be language issue because of the change. I will wait for @craigcook to approve it before I merge it..

**Review by craigcook — APPROVED** [review]

**Comment by stevejalim** [comment]
@peiying2 This is ready for a merge - I seem to lack merge permissions for this repo

**Pull request merged**
