### PR TITLE
Updates from bedrock

### PR DESCRIPTION
**Pull request by MozmarRobot**
From file changes in https://github.com/mozilla/bedrock/commit/5f15398f480eae9f9af35775efe097503b838ce1

### CODE REVIEW

**Review by peiying2 — COMMENTED** [review]
@craigcook should we include the English file that needs to be removed in the PR?

**Comment by craigcook** [comment]
The file was [deleted in bedrock](https://github.com/mozilla/bedrock/commit/5f15398f480eae9f9af35775efe097503b838ce1#diff-296599fd0517a50d03574ec3ac7f72d70dea1b4d6fce4e9815b7b42a78331cfe) so this is another case of the automation not deleting, I think we have to do it manually in a separate PR (or I might be able to manually add a commit to this PR).

**Comment by peiying2** [comment]
> The file was [deleted in bedrock](https://github.com/mozilla/bedrock/commit/5f15398f480eae9f9af35775efe097503b838ce1#diff-296599fd0517a50d03574ec3ac7f72d70dea1b4d6fce4e9815b7b42a78331cfe) so this is another case of the automation not deleting, I think we have to do it manually in a separate PR (or I might be able to manually add a commit to this PR).

Yeah, either way works.

**Comment by craigcook** [comment]
I couldn't add a commit to this PR directly so I opened https://github.com/mozilla-l10n/www-l10n/pull/402

**Review by peiying2 — APPROVED** [review]

**Pull request merged**
