### PR TITLE
Updates from bedrock

### PR DESCRIPTION
**Pull request by MozmarRobot**
From file changes in https://github.com/mozilla/bedrock/commit/14db42961fb482b39242c1073038e6ed3ba4d846

### CODE REVIEW

**Comment by peiying2** [comment]
@craigcook somehow I got a new PR triggered by activity from bedrock, reverting the fixes you did. Let's make sure nothing strange happens. I do have a few issues reported from yesterday's push. I will file an issue on that.

**Comment by pmac** [comment]
the automation from bedrock keeps these files updated to whatever is in bedrock. If they're updated here directly and not in bedrock then bedrock will override them on the next update.

**Comment by craigcook** [comment]
Doh, sorry for making such a mess. I've updated bedrock PR https://github.com/mozilla/bedrock/pull/9794 and removed the `[skip l10n]` so once that merges it should update this PR and maybe fix all the things.

**Review by peiying2 — APPROVED** [review]
Looks good now. Let's hope this resolves the issues.

**Pull request merged**
