### PR TITLE
add features/bookmarks.ftl

### PR DESCRIPTION
**Pull request by craigcook**
The redesigned page isn't yet on dev but we're aiming to merge soon.

Bedrock PR: https://github.com/mozilla/bedrock/pull/9105

### CODE REVIEW

**Comment by craigcook** [comment]
Yeah, "futz" is a strange word. I'm also not happy with "exactitude" and there are other similarly untranslatable words in this batch of pages. They really need to be rewritten some day... 

I'm happy to make an en-US localization and change the canonical file to something more neutral. But then wouldn't that treat this as a new string and wouldn't migrate existing translations? Or would we keep everything as it already is and just edit the English without rerunning the migration script? Would that break anything?

**Comment by peiying2** [comment]
In case I am not explaining well, we still need an `en` file. For the `en-US` version, only include the string that is different from the `en`. Here is an example: https://github.com/mozilla-l10n/www-l10n/blob/master/en-US/firefox/installer-help.ftl

**Comment by craigcook** [comment]
OK, I'll change these in the canonical file (which I forgot to add, but will do next) and treat them as updates with new IDs, and we can keep "futz" and "exactitude" as fallback strings so we don't lose existing translations.

**Comment by peiying2** [comment]
I am thinking some of the comments we add for certain expressions might be opportunities for a revision to make it simpler and remove the comments all together.

**Comment by craigcook** [comment]
Yeah, I've been working with Errolyn on these outdated pages and we've been cringing pretty hard at some of the copy. It was a quippy, hipster tone marketing was trying out at the time and I think it failed. So maybe we can use this opportunity to at least fix a few of the worst examples but really I'd love to completely overhaul all of these pages in the near future.

**Comment by peiying2** [comment]
> Yeah, I've been working with Errolyn on these outdated pages and we've been cringing pretty hard at some of the copy. It was a quippy, hipster tone marketing was trying out at the time and I think it failed. So maybe we can use this opportunity to at least fix a few of the worst examples but really I'd love to completely overhaul all of these pages in the near future.

Thanks for the update. Just want to make sure the *obsolete* comment is for future reference. Right now, there is no replacement and it needs to be translated in order for the page to be activated (if not already).

**Pull request merged**
