### PR TITLE
Updates from bedrock

### PR DESCRIPTION
**Pull request by MozmarRobot**
From file changes in https://github.com/mozilla/bedrock/commit/029ae9cbc766d66ca9bbed9a3f640ad4f17d1a0a

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]

**Review by peiying2 — CHANGES_REQUESTED** [review]
@alexgibson Do we need to change the string ID? A lot of languages have localized this string: https://transvision.mozfr.org/string/?entity=mozilla_org/en/firefox/new/desktop.ftl:firefox-desktop-its-your-internet&repo=mozilla_org. If possible we can pick up those strings and change the brand name, then we don't need to change the string ID.

**Comment by alexgibson** [comment]
@peiying2 technically the context of the string hasn't changed, so I don't think we should need a new string ID. Locales are free to update to the brand name variable at any time, so I'm not sure it's worth triggering extra work for it. 

Or would you prefer a developer to manually update the existing occurences?

**Comment by peiying2** [comment]
> @peiying2 technically the meaning of the string hasn't changed, so I don't think we should need a new string ID. Locales are free to update to the brand name variable at any time, so I'm not sure it's worth triggering extra work for it.
> 
> Or would you prefer a developer to manually update the existing occurences?

The thing is the update with the same ID won't trigger those locales already localized to be checked again. It's not considered to be a fuzzy match or new string for these locales.  I don't think Pontoon will detect it and generate a warning because of the missing variant.

**Comment by alexgibson** [comment]
> The thing is the update with the same ID won't trigger those locales already localized to be checked again.

I get that, but I was trying to say maybe it's ok not to trigger another wave of updates for this. Let me see if I can do it manually to save locales the trouble.

**Comment by alexgibson** [comment]
@peiying2 separate PR to update the localized brand names https://github.com/mozilla-l10n/www-l10n/pull/252. Thank you!

**Comment by peiying2** [comment]
This is replaced with PR #252

**Comment by alexgibson** [comment]
@peiying2 please merge this one also. the other PR only updated the localizations, not the source file. Thanks!

**Review by peiying2 — APPROVED** [review]
Sorry about that. Now officially approved, :).

**Pull request merged**
