### PR TITLE
Add MR1 home promo

### PR DESCRIPTION
**Pull request by craigcook**
There are four different promos, randomly selected when the page loads.

It hasn't merged yet so it's not yet available on dev, but it's on a demo server at https://www-demo4.allizom.org/ and you can see all four promos at https://www-demo4.allizom.org/home-test/

### CODE REVIEW

**Comment by peiying2** [comment]
This PR looks good. Given this is limited to just a few locales, you need to add an entry to the pontoon.toml file.

**Comment by craigcook** [comment]
I think it's all locales. We can likely do French and German in-house but otherwise I think it's open to all. I'll confirm.

**Comment by peiying2** [comment]
> I think it's all locales. We can likely do French and German in-house but otherwise I think it's open to all. I'll confirm.

I mis-read your comment: `excluding ...` If this is the case, it might be simpler to enable all, but the excluded locales will be offered on Pontoon too.

**Review by peiying2 — APPROVED** [review]

**Comment by peiying2** [comment]
@craigcook you still need to add an entry of this new file. This page has now showed up in Pontoon. Also in the process, let's make sure en/mozorg/... is sorted in the correct order.

**Pull request merged**
