### PR TITLE
Migrate mission.lang to mission.ftl

### PR DESCRIPTION
**Pull request by Pike**
@pmac, what do you think about this?

### CODE REVIEW

**Comment by Pike** [comment]
I used an old version of `mission.ftl` for this, so this isn't good to merge. But still good to get feedback on.

**Comment by pmac** [comment]
This looks good to me. 

One question I have, and maybe this isn't the best place to discuss this, but since we're going to have pretty rigid buckets for who will translate what, is there any advantage to directories for each of those buckets into which the locale directories live? e.g.

```
root/
    l10n.toml
    staff/
        de/
        ...
    vendor/
        de/
        ...
    community/
        de/
        ...
```

**Comment by Pike** [comment]
Updated the mission pages to the current version on master.

I asked the question about directories in https://github.com/mozilla/bedrock/pull/8092#issuecomment-562559244, but Alex didn't seem thrilled? Also related, https://github.com/mozilla/bedrock/pull/8332.

**Comment by alexgibson** [comment]
To be honest, I’m still trying to fully understand the advantages / disadvantages of either approach. The system is still new to my understanding, so I feel like I’m shaking a black box in some regards. I’m really looking to the L10n team for a recommendation here.

**Comment by pmac** [comment]
Same here. I guess if we had these directories it would be potentially less flexible. But then again maybe it would be more flexible in some ways? I'm thinking it might be possible and easy to configure a situation where we would want community to translate some files that would normally have gone to staff or vendor? We'd be able to have 3 different `de` directories for example, with different sets of files in them. So in the case of `mission.ftl` it has been translated by community in every local already. So in theory we could add those translations to every locale in the `community` directory, and then other pages or new pages could put the right files in the right locales in the right root directories. Does that sound right @Pike or would it not be possible for it to work that way?

**Comment by Pike** [comment]
We can do `l10n/de/staff/**` as well as `l10n/staff/de/**` in project config. It's just a question if we want 100 `community` directories, or 1-3 `ab-CD` ones.

I don't think we should put files in buckets based on who's been doing it in the past, though, but by whom we expect to maintain that content in the future.

**Comment by pmac** [comment]
> I don't think we should put files in buckets based on who's been doing it in the past, though, but by whom we expect to maintain that content in the future.

👍

**Comment by Pike** [comment]
We've talked about the configs on slack a bit, and we'll go ahead with explicit files in the config for now, and think about possibly rearranging files into bucket directories once we have some experience.

**Pull request merged**
