### PR TITLE
Add firefox/all.ftl

### PR DESCRIPTION
**Pull request by alexgibson**
Bedrock PR: https://github.com/mozilla/bedrock/pull/8785

### CODE REVIEW

**Comment by peiying2** [comment]
@alexgibson This is probably the more complex file than the ones I previously reviewed (and I may have missed something there). Here are a few observations. I point you to a few languages but the issues are not limited to just those but much broadly:
- Brand names are not inserted for all locales. 
  - Depending on how each locale treats the names, let's say `{ -brand-name-firefox } browser`  [Firefox browser]  and `{ -brand-name-firefox-browser }` [Firefox Browser]. Most translate the word `browser` in lower case or upper case and some are hyphenated. 
  - Languages in Latin script, have higher chance of conversion, but hyphenated and declensed brand names would drop the variable (pl)
  - Languages in non-Latin scripts 
     - Almost always translate browser or Browser. And if Firefox translated, there is no conversion (pa-IN and several Indic languages)
    - For the Firefox that are unchanged, some are converted but others are not (el, zh-CN). Not sure if it is related to the fonts used when Latin letters are mixed with non-Latin scripts. Notice within the same files, some are converted while others are not.
- The last part in `en` file contains bunch of brand/product names. In the old .lang files, these kinds of strings are moved to the shared files, such as download button file. Can I assume if I see them in `en`, it is expected that they are omitted in the localized files?
- There are section breaking spaces in the `en` file but all these all missing in the localized files. It is more of a readability issue for me to compare the files, nothing critical. I just wonder what cause the removal of the spaces.

**Comment by alexgibson** [comment]
> Brand names are not inserted for all locales.

If some locales have decided to translate the product names differently to how is recommended, then I think that's up to them. They are free to update these translations and make use of the brand name placeable if they would like to do so. I'm not going to try and manually amend all of these in the migrations of existing content, as it's going to take significant effort (and is something that is largely invisible to the end user).

> The last part in en file contains bunch of brand/product names. In the old .lang files, these kinds of strings are moved to the shared files, such as download button file. Can I assume if I see them in en, it is expected that they are omitted in the localized files?

These are new strings that were previously not translated, since they contain only product names. I'm adding them here because we now have `brands.ftl` to leverage. Locales are free to translate them if they wish, else it is perfectly ok for them to fall back to the default english.

> There are section breaking spaces in the en file but all these all missing in the localized files. It is more of a readability issue for me to compare the files, nothing critical. I just wonder what cause the removal of the spaces.

Our migration scripts omit empty new lines, so not something I have control over without a lot of extra manual work.

**Comment by alexgibson** [comment]
Scrolling though, I see this as a common case of "Firefox" not being replaced by a brand name:

```
firefox-all-choose-which-firefox = Επιλέξτε ποιο Firefox θέλετε να αποκτήσετε στη γλώσσα σας
```

Note the original english string is actually this:

```
firefox-all-choose-which-firefox = Choose which Firefox Browser to download in your language
```

So, the migration is not picking it up because locales have chosen to use "Firefox" over "Firefox Browser". This might be a preference, and something we _could_ try and catch and compensate for. But doing all these brand name migrations is already time consuming enough, I'm not sure it is practical to catch everything. Perhaps this is something locales can work on to improve, if they so wish. Thoughts?

**Comment by alexgibson** [comment]
One final question:

> The last part in en file contains bunch of brand/product names. In the old .lang files, these kinds of strings are moved to the shared files, such as download button file. Can I assume if I see them in en, it is expected that they are omitted in the localized files?

Would it be helpful if I copied these over to all the other locale files?

**Comment by Pike** [comment]
> Would it be helpful if I copied these over to all the other locale files? I'm guessing there's potential that it may effect locale activation if I don't?

Yes. I left a comment in https://github.com/mozilla/bedrock/pull/8785 where you could do this. Or you just paste them below the files, of course.

**Comment by alexgibson** [comment]
Rebased and added new product name strings for all locales.

**Comment by peiying2** [comment]
I will merge this PR. The CSS issue I raised initially is not really an CSS issue from what I can tell after checking them again. As you mentioned, Firefox is picked up as a placeholder but Firefox Browsers are not, and many translated the brand too, so it is a mix bag of issues at locale level. I will make a note in the communication on post migration cleanup, which is up to each community to follow through.

**Pull request merged**
