### PR TITLE
Updates from bedrock

### PR DESCRIPTION
**Pull request by MozmarRobot**
From file changes in https://github.com/mozilla/bedrock/commit/37dbc5e01927a81f12724ec3a317b0b7103a9a00

### CODE REVIEW

**Comment by alexgibson** [comment]
@peiying2 this is for https://github.com/mozilla/bedrock/pull/10295

Note that the page does not yet exist on www-dev, but we'd like to get these strings out as early as we can to give community as much time as possible.

The locales are constrained to: "de", "fr", "it", "nl", "es-ES"

**Review by peiying2 — APPROVED** [review]
Looks good. I am curious why we list the countries in the order we have here, ;).

**Comment by alexgibson** [comment]
> Looks good. I am curious why we list the countries in the order we have here, ;).

Heh, that's on me. es-ES was added late. Still this should cause no harm, thanks

**Comment by peiying2** [comment]
> > Looks good. I am curious why we list the countries in the order we have here, ;).
> 
> Heh, that's on me. es-ES was added late. Still this should cause no harm, thanks

Oh, I missed your part! I meant the countries in the text for translation.

**Comment by alexgibson** [comment]
Oh! you mean `Germany, France, Italy, Spain, Belgium, Austria, Switzerland.` ?

I believe this is ordered according potential to size / audience

**Pull request merged**
